# Generated by Django 3.0.5 on 2020-04-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=60)),
                ('course_time', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('class_week_start', models.IntegerField()),
                ('class_week_end', models.IntegerField()),
            ],
        ),
    ]
