# Generated by Django 3.0.5 on 2020-04-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_coursetable_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetable',
            name='class_week_end',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='coursetable',
            name='class_week_start',
            field=models.IntegerField(default=1),
        ),
    ]
