# Generated by Django 3.0.5 on 2020-04-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=60)),
                ('course_time', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('class_week_start', models.IntegerField(default=1)),
                ('class_week_end', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=60)),
                ('credit', models.FloatField(default=-1.0)),
                ('score', models.IntegerField(default=-1)),
                ('passed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=30)),
                ('test_date', models.CharField(max_length=15)),
                ('test_time', models.CharField(max_length=10)),
                ('test_place', models.CharField(max_length=20)),
                ('seat_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
