# Generated by Django 3.0.5 on 2020-04-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetable',
            name='student_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
