# Generated by Django 3.0.5 on 2020-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200408_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=60)),
                ('credit', models.FloatField(default=-1.0)),
                ('score', models.IntegerField(default=-1)),
                ('passed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=30)),
                ('test_date', models.CharField(max_length=15)),
                ('test_time', models.CharField(max_length=10)),
                ('test_place', models.CharField(max_length=20)),
                ('seat_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='coursetable',
            name='place',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
